import { chromium } from "playwright";
const b = await chromium.launch();
const errs = [];
const ctx = await b.newContext({ viewport: { width: 1440, height: 1000 }, serviceWorkers: "block" });
const page = await ctx.newPage();
page.on("pageerror", (e) => errs.push(e.message));
await page.goto("http://127.0.0.1:8000/stats", { waitUntil: "load" });
await page.waitForFunction(() => /posted in/.test(document.getElementById("trend-summary")?.textContent || ""), null, { timeout: 45000 });
await page.waitForTimeout(600);
console.log("default:", (await page.textContent("#trend-summary")).trim().replace(/\s+/g, " ").slice(0, 150));
console.log("chart drawn:", await page.locator(".xline-path").count(), "paths | settling dashed:", await page.locator(".xline-settling").count());
await page.screenshot({ path: "tests/e2e/trend-panel.png", clip: { x: 0, y: 100, width: 1440, height: 420 } });
await page.selectOption("#trend-days", "90");
await page.waitForTimeout(2500);
console.log("90 days:", (await page.textContent("#trend-summary")).trim().replace(/\s+/g, " ").slice(0, 90));
await page.selectOption("#trend-country", "");
await page.waitForTimeout(2500);
console.log("everywhere:", (await page.textContent("#trend-summary")).trim().replace(/\s+/g, " ").slice(0, 90));
await page.uncheck("#trend-tech");
await page.waitForTimeout(2500);
console.log("all roles:", (await page.textContent("#trend-summary")).trim().replace(/\s+/g, " ").slice(0, 90));
await ctx.close();
await b.close();
console.log(errs.length ? "PAGE ERRORS: " + errs.join(" | ") : "no page errors");
